version: '3.8'

services:
  # PostgreSQL Database - same as base
  postgres:
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Express TSOA API - hidden behind reverse proxy
  api:
    # Remove direct port exposure in production
    ports: []
    networks:
      - app-network

  # React Frontend - hidden behind reverse proxy
  frontend:
    environment:
      NODE_ENV: production
      # Use relative URL since everything goes through nginx
      REACT_APP_API_URL: ""
    # Remove direct port exposure in production
    ports: []
    networks:
      - app-network

  # Nginx Reverse Proxy - main entry point
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Add SSL certificates volume if needed
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  # Dozzle - log viewer (optional, can be removed in production)
  dozzle:
    ports:
      - "9999:8080"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
